1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)


In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

3. Create a null vector of size 10

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array


In [4]:
print(np.size(z))
print(z.itemsize)

10
8


5. How to get the documentation of the numpy add function from the command line? 


In [5]:
print(np.info())
#%run `python -c "import numpy; numpy.info(numpy.add)"`

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fd74056c290>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

6. Create a null vector of size 10 but the fifth value which is 1


In [7]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [8]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [9]:
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)
(hint: np.eye)

In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)
(hint: np.random.random)

In [13]:
z = np.random.random((3,3,3))
print (z)


[[[0.64492866 0.43211094 0.51664436]
  [0.88220943 0.31085117 0.51478534]
  [0.63691652 0.01102463 0.2875617 ]]

 [[0.90686827 0.16655264 0.40958742]
  [0.31275271 0.85641544 0.98918498]
  [0.9616876  0.00544557 0.40591476]]

 [[0.50229222 0.34621789 0.81427348]
  [0.47299894 0.40416614 0.32304944]
  [0.26098637 0.11768223 0.91224859]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(hint: min, max)

In [14]:
z = np.random.random((10,10))
print(z.min(),z.max())

0.002104451748312419 0.9931678122676273
